[package]
name = "dev-null-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
dotenv = "0.15.0"
hyper = { version = "0.14.26", features = ["full"] }
lettre = "0.10.4"
notify = "6.0.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.1", features = ["full"] }
tower = "0.4.13"
tracing-subscriber = "0.3.17"
